//using System;
//using System.Collections.Generic;
//using System.Linq;
//using System.Text;
//using System.Threading.Tasks;
//using System.Data.Entity;

//namespace DiaryOfSportsNutrition_Andrianova
//{
//    public class MyInitializer : DropCreateDatabaseAlways<DiaryNutrionContext>/* DropCreateDatabaseIfModelChanges<DiaryNutrionContext>*/
//    {

//        protected override void Seed(DiaryNutrionContext context)
//        {
//            IList<Food> products = new List<Food>();
//            products.Add(new Food { FoodName = "Абрикосы", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 45 });
//            products.Add(new Food { FoodName = "Авокадо", Proteins = 2, Fat = 19, Carbohydrates = 7, CaloricValue = 197 });
//            products.Add(new Food { FoodName = "Аджика", Proteins = 2, Fat = 3, Carbohydrates = 8, CaloricValue = 59 });
//            products.Add(new Food { FoodName = "Айва", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
//            products.Add(new Food { FoodName = "Айсберг", Proteins = 1, Fat = 0, Carbohydrates = 2, CaloricValue = 17 });
//            products.Add(new Food { FoodName = "Активиа кефирная 1%", Proteins = 3, Fat = 1, Carbohydrates = 4, CaloricValue = 39 });
//            products.Add(new Food { FoodName = "Ананас", Proteins = 0, Fat = 0, Carbohydrates = 12, CaloricValue = 50 });
//            products.Add(new Food { FoodName = "Ананас консервированный", Proteins = 0, Fat = 0, Carbohydrates = 16, CaloricValue = 65 });
//            products.Add(new Food { FoodName = "Ананас цукаты", Proteins = 1, Fat = 2, Carbohydrates = 15, CaloricValue = 78 });
//            products.Add(new Food { FoodName = "Апельсин", Proteins = 2, Fat = 0, Carbohydrates = 9, CaloricValue = 43 });
//            products.Add(new Food { FoodName = "Апельсиновый сок", Proteins = 0, Fat = 0, Carbohydrates = 11, CaloricValue = 44 });
//            products.Add(new Food { FoodName = "Арахис", Proteins = 25, Fat = 46, Carbohydrates = 13, CaloricValue = 561 });
//            products.Add(new Food { FoodName = "Арахис в сахаре", Proteins = 18, Fat = 30, Carbohydrates = 51, CaloricValue = 535 });
//            products.Add(new Food { FoodName = "Базилик свежий", Proteins = 3, Fat = 1, Carbohydrates = 4, CaloricValue = 27 });
//            products.Add(new Food { FoodName = "Баклажаны", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 27 });
//            products.Add(new Food { FoodName = "Банан", Proteins = 3, Fat = 3, Carbohydrates = 22, CaloricValue = 97 });
//            products.Add(new Food { FoodName = "Баранина вареная", Proteins = 24, Fat = 21, Carbohydrates = 0, CaloricValue = 286 });
//            products.Add(new Food { FoodName = "Батон", Proteins = 8, Fat = 3, Carbohydrates = 49, CaloricValue = 264 });
//            products.Add(new Food { FoodName = "Бедро индейки", Proteins = 16, Fat = 9, Carbohydrates = 1, CaloricValue = 143 });
//            products.Add(new Food { FoodName = "Бекон", Proteins = 15, Fat = 45, Carbohydrates = 2, CaloricValue = 469 });
//            products.Add(new Food { FoodName = "Блины обычные", Proteins = 6, Fat = 6, Carbohydrates = 25, CaloricValue = 178 });
//            products.Add(new Food { FoodName = "Борщ лёгкий", Proteins = 3, Fat = 2, Carbohydrates = 9, CaloricValue = 58 });
//            products.Add(new Food { FoodName = "Брокколи", Proteins = 4, Fat = 1, Carbohydrates = 4, CaloricValue = 33 });
//            products.Add(new Food { FoodName = "Брусника", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 42 });
//            products.Add(new Food { FoodName = "Бульон из говядины", Proteins = 6, Fat = 4, Carbohydrates = 0, CaloricValue = 57 });
//            products.Add(new Food { FoodName = "Бульон из куриной грудки", Proteins = 7, Fat = 1, Carbohydrates = 0, CaloricValue = 42 });
//            products.Add(new Food { FoodName = "Бульон куриный", Proteins = 3, Fat = 2, Carbohydrates = 1, CaloricValue = 33 });
//            products.Add(new Food { FoodName = "Вареная говядина", Proteins = 23, Fat = 16, Carbohydrates = 0, CaloricValue = 236 });
//            products.Add(new Food { FoodName = "Вареная колбаса", Proteins = 12, Fat = 22, Carbohydrates = 1, CaloricValue = 253 });
//            products.Add(new Food { FoodName = "Вареная куриная грудка", Proteins = 27, Fat = 6, Carbohydrates = 1, CaloricValue = 138 });
//            products.Add(new Food { FoodName = "Вареная курица", Proteins = 19, Fat = 9, Carbohydrates = 0, CaloricValue = 150 });
//            products.Add(new Food { FoodName = "Вареная морковь", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 31 });
//            products.Add(new Food { FoodName = "Вареная чечевица", Proteins = 8, Fat = 0, Carbohydrates = 20, CaloricValue = 111 });
//            products.Add(new Food { FoodName = "Варёная сгущёнка", Proteins = 7, Fat = 9, Carbohydrates = 55, CaloricValue = 326 });
//            products.Add(new Food { FoodName = "Вермишель", Proteins = 11, Fat = 1, Carbohydrates = 72, CaloricValue = 347 });
//            products.Add(new Food { FoodName = "Ветчина", Proteins = 16, Fat = 19, Carbohydrates = 2, CaloricValue = 246 });
//            products.Add(new Food { FoodName = "Вино белое сухое", Proteins = 0, Fat = 0, Carbohydrates = 0, CaloricValue = 67 });
//            products.Add(new Food { FoodName = "Виноград", Proteins = 1, Fat = 1, Carbohydrates = 16, CaloricValue = 69 });
//            products.Add(new Food { FoodName = "Вино красное сухое", Proteins = 0, Fat = 0, Carbohydrates = 1, CaloricValue = 70 });
//            products.Add(new Food { FoodName = "Вишня", Proteins = 1, Fat = 0, Carbohydrates = 11, CaloricValue = 54 });
//            products.Add(new Food { FoodName = "Геркулес", Proteins = 12, Fat = 6, Carbohydrates = 56, CaloricValue = 327 });
//            products.Add(new Food { FoodName = "Говядина", Proteins = 20, Fat = 13, Carbohydrates = 0, CaloricValue = 192 });
//            products.Add(new Food { FoodName = "Говяжья печень", Proteins = 17, Fat = 3, Carbohydrates = 3, CaloricValue = 110 });
//            products.Add(new Food { FoodName = "Голень куриная", Proteins = 20, Fat = 9, Carbohydrates = 0, CaloricValue = 168 });
//            products.Add(new Food { FoodName = "Голландский сыр", Proteins = 24, Fat = 30, Carbohydrates = 0, CaloricValue = 373 });
//            products.Add(new Food { FoodName = "Голубика", Proteins = 1, Fat = 1, Carbohydrates = 9, CaloricValue = 46 });
//            products.Add(new Food { FoodName = "Горбуша", Proteins = 21, Fat = 7, Carbohydrates = 0, CaloricValue = 143 });
//            products.Add(new Food { FoodName = "Горох", Proteins = 19, Fat = 3, Carbohydrates = 42, CaloricValue = 256 });
//            products.Add(new Food { FoodName = "Гороховое пюре", Proteins = 8, Fat = 1, Carbohydrates = 23, CaloricValue = 106 });
//            products.Add(new Food { FoodName = "Горошек зеленый", Proteins = 4, Fat = 0, Carbohydrates = 10, CaloricValue = 59 });
//            products.Add(new Food { FoodName = "Горчица", Proteins = 8, Fat = 11, Carbohydrates = 13, CaloricValue = 184 });
//            products.Add(new Food { FoodName = "Гранат", Proteins = 2, Fat = 1, Carbohydrates = 14, CaloricValue = 67 });
//            products.Add(new Food { FoodName = "Грейпфрут", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
//            products.Add(new Food { FoodName = "Грецкие орехи", Proteins = 15, Fat = 65, Carbohydrates = 14, CaloricValue = 697 });
//            products.Add(new Food { FoodName = "Гречневая каша рассыпчатая", Proteins = 5, Fat = 1, Carbohydrates = 24, CaloricValue = 131 });
//            products.Add(new Food { FoodName = "Гречневая крупа", Proteins = 12, Fat = 4, Carbohydrates = 63, CaloricValue = 329 });
//            products.Add(new Food { FoodName = "Грибы белые", Proteins = 9, Fat = 2, Carbohydrates = 3, CaloricValue = 28 });
//            products.Add(new Food { FoodName = "Грибы белые сушеные", Proteins = 27, Fat = 7, Carbohydrates = 16, CaloricValue = 239 });
//            products.Add(new Food { FoodName = "Грибы грузди", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 16 });
//            products.Add(new Food { FoodName = "Грибы лисички", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 20 });
//            products.Add(new Food { FoodName = "Грибы маслята", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 9 });
//            products.Add(new Food { FoodName = "Грибы опята", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 17 });
//            products.Add(new Food { FoodName = "Грибы подберёзовики свежие", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 17 });
//            products.Add(new Food { FoodName = "Грибы шампиньоны", Proteins = 4, Fat = 1, Carbohydrates = 0, CaloricValue = 22 });
//            products.Add(new Food { FoodName = "Груша", Proteins = 1, Fat = 0, Carbohydrates = 12, CaloricValue = 51 });
//            products.Add(new Food { FoodName = "Груша (сухофрукты)", Proteins = 2, Fat = 0, Carbohydrates = 62, CaloricValue = 246 });
//            products.Add(new Food { FoodName = "Дайкон", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 21 });
//            products.Add(new Food { FoodName = "Джем мандариновый", Proteins = 0, Fat = 0, Carbohydrates = 72, CaloricValue = 276 });
//            products.Add(new Food { FoodName = "Дрожжи", Proteins = 29, Fat = 3, Carbohydrates = 23, CaloricValue = 263 });
//            products.Add(new Food { FoodName = "Дыня", Proteins = 1, Fat = 0, Carbohydrates = 8, CaloricValue = 35 });
//            products.Add(new Food { FoodName = "Ежевика", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 31 });
//            products.Add(new Food { FoodName = "Жареное яйцо", Proteins = 14, Fat = 14, Carbohydrates = 1, CaloricValue = 183 });
//            products.Add(new Food { FoodName = "Зеленая фасоль", Proteins = 3, Fat = 0, Carbohydrates = 4, CaloricValue = 30 });
//            products.Add(new Food { FoodName = "Зеленый лук", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 19 });
//            products.Add(new Food { FoodName = "Зелень петрушки", Proteins = 4, Fat = 0, Carbohydrates = 8, CaloricValue = 50 });
//            products.Add(new Food { FoodName = "Зелёный горошек \"Бондюэль\"", Proteins = 5, Fat = 0, Carbohydrates = 8, CaloricValue = 60 });
//            products.Add(new Food { FoodName = "Земляника", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 38 });
//            products.Add(new Food { FoodName = "Зефир бело-розовый", Proteins = 1, Fat = 0, Carbohydrates = 80, CaloricValue = 304 });
//            products.Add(new Food { FoodName = "Изюм", Proteins = 2, Fat = 0, Carbohydrates = 68, CaloricValue = 280 });
//            products.Add(new Food { FoodName = "Имбирь свежий", Proteins = 2, Fat = 1, Carbohydrates = 16, CaloricValue = 72 });
//            products.Add(new Food { FoodName = "Индейка (грудка)", Proteins = 19, Fat = 2, Carbohydrates = 0, CaloricValue = 94 });
//            products.Add(new Food { FoodName = "Индейка (филе)", Proteins = 20, Fat = 12, Carbohydrates = 0, CaloricValue = 188 });
//            products.Add(new Food { FoodName = "Инжир (сухофрукты)", Proteins = 3, Fat = 1, Carbohydrates = 57, CaloricValue = 239 });
//            products.Add(new Food { FoodName = "Йогурт Активия", Proteins = 4, Fat = 3, Carbohydrates = 11, CaloricValue = 97 });
//            products.Add(new Food { FoodName = "Кабачки жареные", Proteins = 1, Fat = 6, Carbohydrates = 7, CaloricValue = 91 });
//            products.Add(new Food { FoodName = "Кабачки цукини", Proteins = 2, Fat = 0, Carbohydrates = 3, CaloricValue = 16 });
//            products.Add(new Food { FoodName = "Кабачковая икра", Proteins = 1, Fat = 6, Carbohydrates = 7, CaloricValue = 90 });
//            products.Add(new Food { FoodName = "Какао", Proteins = 14, Fat = 9, Carbohydrates = 26, CaloricValue = 234 });
//            products.Add(new Food { FoodName = "Какао порошок", Proteins = 23, Fat = 15, Carbohydrates = 29, CaloricValue = 326 });
//            products.Add(new Food { FoodName = "Кальмар", Proteins = 18, Fat = 2, Carbohydrates = 1, CaloricValue = 97 });
//            products.Add(new Food { FoodName = "Кальмар вареный", Proteins = 18, Fat = 3, Carbohydrates = 1, CaloricValue = 103 });
//            products.Add(new Food { FoodName = "Каперсы", Proteins = 2, Fat = 1, Carbohydrates = 4, CaloricValue = 21 });
//            products.Add(new Food { FoodName = "Капуста белокочаная", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 28 });
//            products.Add(new Food { FoodName = "Капуста брокколи замороженая", Proteins = 0, Fat = 0, Carbohydrates = 4, CaloricValue = 21 });
//            products.Add(new Food { FoodName = "Капуста брюссельская", Proteins = 4, Fat = 0, Carbohydrates = 4, CaloricValue = 47 });
//            products.Add(new Food { FoodName = "Капуста жареная", Proteins = 3, Fat = 6, Carbohydrates = 8, CaloricValue = 88 });
//            products.Add(new Food { FoodName = "Капуста квашенная", Proteins = 2, Fat = 0, Carbohydrates = 3, CaloricValue = 23 });
//            products.Add(new Food { FoodName = "Капуста морская", Proteins = 1, Fat = 5, Carbohydrates = 0, CaloricValue = 58 });
//            products.Add(new Food { FoodName = "Капуста цветная", Proteins = 3, Fat = 0, Carbohydrates = 5, CaloricValue = 34 });
//            products.Add(new Food { FoodName = "Картофель", Proteins = 2, Fat = 1, Carbohydrates = 20, CaloricValue = 84 });
//            products.Add(new Food { FoodName = "Картофель молодой", Proteins = 2, Fat = 0, Carbohydrates = 16, CaloricValue = 61 });
//            products.Add(new Food { FoodName = "Картофель отварной", Proteins = 2, Fat = 1, Carbohydrates = 16, CaloricValue = 83 });
//            products.Add(new Food { FoodName = "Картофель печеный", Proteins = 3, Fat = 3, Carbohydrates = 22, CaloricValue = 113 });
//            products.Add(new Food { FoodName = "Картофель фри", Proteins = 4, Fat = 17, Carbohydrates = 40, CaloricValue = 323 });
//            products.Add(new Food { FoodName = "Каша рисовая", Proteins = 2, Fat = 3, Carbohydrates = 26, CaloricValue = 130 });
//            products.Add(new Food { FoodName = "Квас хлебный", Proteins = 0, Fat = 0, Carbohydrates = 5, CaloricValue = 24 });
//            products.Add(new Food { FoodName = "Кедровые орехи", Proteins = 15, Fat = 63, Carbohydrates = 17, CaloricValue = 652 });
//            products.Add(new Food { FoodName = "Кефир 1%", Proteins = 3, Fat = 1, Carbohydrates = 5, CaloricValue = 45 });
//            products.Add(new Food { FoodName = "Кефир 2,5%", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 52 });
//            products.Add(new Food { FoodName = "Кефир 3,2%", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 58 });
//            products.Add(new Food { FoodName = "Кешью", Proteins = 21, Fat = 48, Carbohydrates = 20, CaloricValue = 607 });
//            products.Add(new Food { FoodName = "Киви", Proteins = 1, Fat = 1, Carbohydrates = 10, CaloricValue = 51 });
//            products.Add(new Food { FoodName = "Клубника", Proteins = 1, Fat = 0, Carbohydrates = 7, CaloricValue = 32 });
//            products.Add(new Food { FoodName = "Клюква", Proteins = 0, Fat = 0, Carbohydrates = 9, CaloricValue = 43 });
//            products.Add(new Food { FoodName = "Конфеты Батончики Рот Фронт с орехами", Proteins = 12, Fat = 32, Carbohydrates = 49, CaloricValue = 379 });
//            products.Add(new Food { FoodName = "Коричневый сахар", Proteins = 0, Fat = 0, Carbohydrates = 92, CaloricValue = 393 });
//            products.Add(new Food { FoodName = "Котлеты полтавские", Proteins = 26, Fat = 32, Carbohydrates = 6, CaloricValue = 415 });
//            products.Add(new Food { FoodName = "Кофе молотый Арабика", Proteins = 12, Fat = 14, Carbohydrates = 3, CaloricValue = 193 });
//            products.Add(new Food { FoodName = "Кофе эспрессо крепкий", Proteins = 1, Fat = 2, Carbohydrates = 0, CaloricValue = 19 });
//            products.Add(new Food { FoodName = "Кофе \"якобз монарх\" (растворимый)", Proteins = 15, Fat = 0, Carbohydrates = 8, CaloricValue = 97 });
//            products.Add(new Food { FoodName = "Крабовые палочки", Proteins = 8, Fat = 2, Carbohydrates = 10, CaloricValue = 85 });
//            products.Add(new Food { FoodName = "Краковская колбаса", Proteins = 17, Fat = 39, Carbohydrates = 0, CaloricValue = 420 });
//            products.Add(new Food { FoodName = "Креветки (отварные)", Proteins = 18, Fat = 2, Carbohydrates = 0, CaloricValue = 90 });
//            products.Add(new Food { FoodName = "Крупа гречневая", Proteins = 12, Fat = 3, Carbohydrates = 65, CaloricValue = 326 });
//            products.Add(new Food { FoodName = "Крупа кукурузная", Proteins = 8, Fat = 1, Carbohydrates = 75, CaloricValue = 337 });
//            products.Add(new Food { FoodName = "Крупа манная", Proteins = 11, Fat = 1, Carbohydrates = 70, CaloricValue = 330 });
//            products.Add(new Food { FoodName = "Крупа овсяная", Proteins = 12, Fat = 6, Carbohydrates = 65, CaloricValue = 328 });
//            products.Add(new Food { FoodName = "Крупа рис длиннозерный пропаренный", Proteins = 7, Fat = 1, Carbohydrates = 74, CaloricValue = 333 });
//            products.Add(new Food { FoodName = "Крупа рисовая", Proteins = 7, Fat = 11, Carbohydrates = 63, CaloricValue = 330 });
//            products.Add(new Food { FoodName = "Крыжовник", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 41 });
//            products.Add(new Food { FoodName = "Кукуруза консервированная", Proteins = 3, Fat = 2, Carbohydrates = 17, CaloricValue = 87 });
//            products.Add(new Food { FoodName = "Кукурузные хлопья", Proteins = 6, Fat = 3, Carbohydrates = 73, CaloricValue = 353 });
//            products.Add(new Food { FoodName = "Курага", Proteins = 5, Fat = 0, Carbohydrates = 54, CaloricValue = 232 });
//            products.Add(new Food { FoodName = "Куриная печень", Proteins = 19, Fat = 7, Carbohydrates = 1, CaloricValue = 140 });
//            products.Add(new Food { FoodName = "Куриные грудки", Proteins = 23, Fat = 6, Carbohydrates = 3, CaloricValue = 144 });
//            products.Add(new Food { FoodName = "Куриные окорочка", Proteins = 18, Fat = 11, Carbohydrates = 0, CaloricValue = 170 });
//            products.Add(new Food { FoodName = "Курица", Proteins = 21, Fat = 11, Carbohydrates = 1, CaloricValue = 186 });
//            products.Add(new Food { FoodName = "Лаваш грузинский", Proteins = 8, Fat = 2, Carbohydrates = 53, CaloricValue = 269 });
//            products.Add(new Food { FoodName = "Лайм", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 20 });
//            products.Add(new Food { FoodName = "Лапша яичная", Proteins = 10, Fat = 2, Carbohydrates = 64, CaloricValue = 330 });
//            products.Add(new Food { FoodName = "Лимон", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 27 });
//            products.Add(new Food { FoodName = "Лосось", Proteins = 21, Fat = 10, Carbohydrates = 1, CaloricValue = 172 });
//            products.Add(new Food { FoodName = "Лук", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 40 });
//            products.Add(new Food { FoodName = "Майонез", Proteins = 2, Fat = 57, Carbohydrates = 4, CaloricValue = 550 });
//            products.Add(new Food { FoodName = "Майонез 15%", Proteins = 0, Fat = 15, Carbohydrates = 5, CaloricValue = 156 });
//            products.Add(new Food { FoodName = "Майонез провансаль 67%", Proteins = 3, Fat = 69, Carbohydrates = 25, CaloricValue = 619 });
//            products.Add(new Food { FoodName = "Макароны отварные", Proteins = 4, Fat = 1, Carbohydrates = 23, CaloricValue = 119 });
//            products.Add(new Food { FoodName = "Малина", Proteins = 4, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
//            products.Add(new Food { FoodName = "Манго", Proteins = 1, Fat = 0, Carbohydrates = 13, CaloricValue = 62 });
//            products.Add(new Food { FoodName = "Мандарин", Proteins = 1, Fat = 1, Carbohydrates = 9, CaloricValue = 40 });
//            products.Add(new Food { FoodName = "Маргарин молочный", Proteins = 0, Fat = 82, Carbohydrates = 6, CaloricValue = 745 });
//            products.Add(new Food { FoodName = "Мармелад", Proteins = 1, Fat = 0, Carbohydrates = 75, CaloricValue = 302 });
//            products.Add(new Food { FoodName = "Маслины", Proteins = 1, Fat = 14, Carbohydrates = 10, CaloricValue = 167 });
//            products.Add(new Food { FoodName = "Масло оливковое", Proteins = 1, Fat = 91, Carbohydrates = 3, CaloricValue = 851 });
//            products.Add(new Food { FoodName = "Масло подсолнечное", Proteins = 0, Fat = 96, Carbohydrates = 0, CaloricValue = 864 });
//            products.Add(new Food { FoodName = "Масло сливочное", Proteins = 1, Fat = 74, Carbohydrates = 1, CaloricValue = 674 });
//            products.Add(new Food { FoodName = "Мед", Proteins = 1, Fat = 0, Carbohydrates = 80, CaloricValue = 315 });
//            products.Add(new Food { FoodName = "Миндаль", Proteins = 18, Fat = 51, Carbohydrates = 16, CaloricValue = 601 });
//            products.Add(new Food { FoodName = "Молоко 0,5%", Proteins = 2, Fat = 1, Carbohydrates = 3, CaloricValue = 35 });
//            products.Add(new Food { FoodName = "Молоко 1,5%", Proteins = 3, Fat = 2, Carbohydrates = 5, CaloricValue = 44 });
//            products.Add(new Food { FoodName = "Молоко 2,5%", Proteins = 3, Fat = 3, Carbohydrates = 7, CaloricValue = 64 });
//            products.Add(new Food { FoodName = "Молоко 3,2%", Proteins = 3, Fat = 3, Carbohydrates = 8, CaloricValue = 67 });
//            products.Add(new Food { FoodName = "Молоко сгущёное", Proteins = 7, Fat = 9, Carbohydrates = 56, CaloricValue = 317 });
//            products.Add(new Food { FoodName = "Морковь свежая", Proteins = 1, Fat = 0, Carbohydrates = 8, CaloricValue = 35 });
//            products.Add(new Food { FoodName = "Мороженое Пломбир", Proteins = 4, Fat = 15, Carbohydrates = 24, CaloricValue = 245 });
//            products.Add(new Food { FoodName = "Морская капуста", Proteins = 1, Fat = 2, Carbohydrates = 2, CaloricValue = 37 });
//            products.Add(new Food { FoodName = "Мюстли с фруктами", Proteins = 8, Fat = 2, Carbohydrates = 68, CaloricValue = 314 });
//            products.Add(new Food { FoodName = "Мясо свинина", Proteins = 26, Fat = 29, Carbohydrates = 7, CaloricValue = 293 });
//            products.Add(new Food { FoodName = "Мясо свинина постная", Proteins = 18, Fat = 8, Carbohydrates = 0, CaloricValue = 151 });
//            products.Add(new Food { FoodName = "Овощная смесь “Весенние овощи”", Proteins = 3, Fat = 0, Carbohydrates = 4, CaloricValue = 30 });
//            products.Add(new Food { FoodName = "Овсянка", Proteins = 9, Fat = 5, Carbohydrates = 46, CaloricValue = 240 });
//            products.Add(new Food { FoodName = "Овсянные хлопья \"геркулес\"", Proteins = 11, Fat = 6, Carbohydrates = 51, CaloricValue = 305 });
//            products.Add(new Food { FoodName = "Огурцы", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 19 });
//            products.Add(new Food { FoodName = "Огурцы маринованные", Proteins = 2, Fat = 0, Carbohydrates = 2, CaloricValue = 16 });
//            products.Add(new Food { FoodName = "Оливки", Proteins = 1, Fat = 17, Carbohydrates = 5, CaloricValue = 178 });
//            products.Add(new Food { FoodName = "Омлет", Proteins = 10, Fat = 14, Carbohydrates = 3, CaloricValue = 175 });
//            products.Add(new Food { FoodName = "Орех грецкий", Proteins = 15, Fat = 64, Carbohydrates = 11, CaloricValue = 671 });
//            products.Add(new Food { FoodName = "Отруби овсяные", Proteins = 15, Fat = 7, Carbohydrates = 45, CaloricValue = 305 });
//            products.Add(new Food { FoodName = "Отруби пшеничные очищенные", Proteins = 13, Fat = 4, Carbohydrates = 23, CaloricValue = 214 });
//            products.Add(new Food { FoodName = "Паприка", Proteins = 3, Fat = 2, Carbohydrates = 7, CaloricValue = 112 });
//            products.Add(new Food { FoodName = "Патиссон", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 19 });
//            products.Add(new Food { FoodName = "Перепелиное яйцо", Proteins = 13, Fat = 13, Carbohydrates = 0, CaloricValue = 167 });
//            products.Add(new Food { FoodName = "Перец сладкий", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 26 });
//            products.Add(new Food { FoodName = "Перловка отварная", Proteins = 2, Fat = 0, Carbohydrates = 27, CaloricValue = 121 });
//            products.Add(new Food { FoodName = "Персики", Proteins = 1, Fat = 1, Carbohydrates = 12, CaloricValue = 51 });
//            products.Add(new Food { FoodName = "Персики (сухофрукты)", Proteins = 2, Fat = 0, Carbohydrates = 42, CaloricValue = 168 });
//            products.Add(new Food { FoodName = "Петрушка свежая", Proteins = 3, Fat = 1, Carbohydrates = 7, CaloricValue = 38 });
//            products.Add(new Food { FoodName = "Печенье", Proteins = 8, Fat = 18, Carbohydrates = 66, CaloricValue = 455 });
//            products.Add(new Food { FoodName = "Пиво светлое", Proteins = 0, Fat = 0, Carbohydrates = 4, CaloricValue = 50 });
//            products.Add(new Food { FoodName = "Плавленный сыр", Proteins = 15, Fat = 20, Carbohydrates = 2, CaloricValue = 280 });
//            products.Add(new Food { FoodName = "Помидоры консервированные", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 23 });
//            products.Add(new Food { FoodName = "Помидоры свежие", Proteins = 4, Fat = 1, Carbohydrates = 3, CaloricValue = 33 });
//            products.Add(new Food { FoodName = "Простокваша", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 52 });
//            products.Add(new Food { FoodName = "Редис", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 20 });
//            products.Add(new Food { FoodName = "Рис отварной", Proteins = 7, Fat = 1, Carbohydrates = 75, CaloricValue = 331 });
//            products.Add(new Food { FoodName = "Рожки отварные", Proteins = 3, Fat = 0, Carbohydrates = 24, CaloricValue = 115 });
//            products.Add(new Food { FoodName = "Руккола", Proteins = 2, Fat = 1, Carbohydrates = 2, CaloricValue = 24 });
//            products.Add(new Food { FoodName = "Рыба скумбрия", Proteins = 16, Fat = 13, Carbohydrates = 1, CaloricValue = 187 });
//            products.Add(new Food { FoodName = "Рыба треска", Proteins = 17, Fat = 1, Carbohydrates = 0, CaloricValue = 80 });
//            products.Add(new Food { FoodName = "Ряженка", Proteins = 3, Fat = 3, Carbohydrates = 4, CaloricValue = 62 });
//            products.Add(new Food { FoodName = "Салат лист", Proteins = 1, Fat = 0, Carbohydrates = 2, CaloricValue = 16 });
//            products.Add(new Food { FoodName = "Сахар песок", Proteins = 0, Fat = 0, Carbohydrates = 100, CaloricValue = 396 });
//            products.Add(new Food { FoodName = "Свежая капуста", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 25 });
//            products.Add(new Food { FoodName = "Свежий укроп", Proteins = 3, Fat = 1, Carbohydrates = 6, CaloricValue = 38 });
//            products.Add(new Food { FoodName = "Свекла", Proteins = 2, Fat = 1, Carbohydrates = 12, CaloricValue = 61 });
//            products.Add(new Food { FoodName = "Сельдь жирная", Proteins = 15, Fat = 15, Carbohydrates = 0, CaloricValue = 204 });
//            products.Add(new Food { FoodName = "Сладкая кукуруза в початках", Proteins = 4, Fat = 3, Carbohydrates = 21, CaloricValue = 124 });
//            products.Add(new Food { FoodName = "Семечки подсолнечные", Proteins = 26, Fat = 50, Carbohydrates = 9, CaloricValue = 583 });
//            products.Add(new Food { FoodName = "Слива садовая", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 45 });
//            products.Add(new Food { FoodName = "Сливки 10%", Proteins = 3, Fat = 10, Carbohydrates = 4, CaloricValue = 118 });
//            products.Add(new Food { FoodName = "Сливки 20%", Proteins = 3, Fat = 20, Carbohydrates = 4, CaloricValue = 206 });
//            products.Add(new Food { FoodName = "Сливки 33%", Proteins = 2, Fat = 33, Carbohydrates = 4, CaloricValue = 322 });
//            products.Add(new Food { FoodName = "Смесь орехов и сухофруктов экзотик", Proteins = 8, Fat = 26, Carbohydrates = 52, CaloricValue = 466 });
//            products.Add(new Food { FoodName = "Сметана 10 %", Proteins = 3, Fat = 10, Carbohydrates = 4, CaloricValue = 118 });
//            products.Add(new Food { FoodName = "Сметана 15%", Proteins = 3, Fat = 15, Carbohydrates = 4, CaloricValue = 129 });
//            products.Add(new Food { FoodName = "Сметана 20%", Proteins = 3, Fat = 19, Carbohydrates = 6, CaloricValue = 204 });
//            products.Add(new Food { FoodName = "Сметана 30 %", Proteins = 2, Fat = 30, Carbohydrates = 3, CaloricValue = 291 });
//            products.Add(new Food { FoodName = "Смородина красная", Proteins = 1, Fat = 0, Carbohydrates = 8, CaloricValue = 40 });
//            products.Add(new Food { FoodName = "Смородина чёрная", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 41 });
//            products.Add(new Food { FoodName = "Соевый соус", Proteins = 5, Fat = 0, Carbohydrates = 22, CaloricValue = 36 });
//            products.Add(new Food { FoodName = "Сок апельсиновый", Proteins = 1, Fat = 0, Carbohydrates = 11, CaloricValue = 47 });
//            products.Add(new Food { FoodName = "Сок грейпфрутовый", Proteins = 0, Fat = 0, Carbohydrates = 10, CaloricValue = 44 });
//            products.Add(new Food { FoodName = "Сок лайма", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 22 });
//            products.Add(new Food { FoodName = "Сок лимонный", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 29 });
//            products.Add(new Food { FoodName = "Сок мандарина", Proteins = 1, Fat = 0, Carbohydrates = 10, CaloricValue = 43 });
//            products.Add(new Food { FoodName = "Сок томатный", Proteins = 0, Fat = 0, Carbohydrates = 5, CaloricValue = 21 });
//            products.Add(new Food { FoodName = "Сок яблочный", Proteins = 0, Fat = 0, Carbohydrates = 10, CaloricValue = 44 });
//            products.Add(new Food { FoodName = "Соя", Proteins = 34, Fat = 12, Carbohydrates = 27, CaloricValue = 359 });
//            products.Add(new Food { FoodName = "Спагетти отварные", Proteins = 7, Fat = 1, Carbohydrates = 46, CaloricValue = 223 });
//            products.Add(new Food { FoodName = "Сухари панировочные", Proteins = 12, Fat = 2, Carbohydrates = 74, CaloricValue = 362 });
//            products.Add(new Food { FoodName = "Сыворотка", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 22 });
//            products.Add(new Food { FoodName = "Сыр 45%", Proteins = 26, Fat = 26, Carbohydrates = 0, CaloricValue = 336 });
//            products.Add(new Food { FoodName = "Сыр 50% «Сливочный»", Proteins = 23, Fat = 28, Carbohydrates = 0, CaloricValue = 288 });
//            products.Add(new Food { FoodName = "Сыр гауда", Proteins = 24, Fat = 27, Carbohydrates = 2, CaloricValue = 350 });
//            products.Add(new Food { FoodName = "Сыр «Лёгкий»", Proteins = 23, Fat = 17, Carbohydrates = 0, CaloricValue = 300 });
//            products.Add(new Food { FoodName = "Сырок плавленный \"Дружба\"", Proteins = 6, Fat = 19, Carbohydrates = 0, CaloricValue = 178 });
//            products.Add(new Food { FoodName = "Сыр твердый", Proteins = 25, Fat = 27, Carbohydrates = 2, CaloricValue = 358 });
//            products.Add(new Food { FoodName = "Тархун", Proteins = 0, Fat = 0, Carbohydrates = 10, CaloricValue = 41 });
//            products.Add(new Food { FoodName = "Творог 0%", Proteins = 16, Fat = 0, Carbohydrates = 2, CaloricValue = 75 });
//            products.Add(new Food { FoodName = "Творог 1%", Proteins = 17, Fat = 1, Carbohydrates = 2, CaloricValue = 82 });
//            products.Add(new Food { FoodName = "Творог 10%", Proteins = 15, Fat = 9, Carbohydrates = 2, CaloricValue = 150 });
//            products.Add(new Food { FoodName = "Творог 5 %", Proteins = 17, Fat = 5, Carbohydrates = 2, CaloricValue = 122 });
//            products.Add(new Food { FoodName = "Творог 9%", Proteins = 16, Fat = 8, Carbohydrates = 3, CaloricValue = 153 });
//            products.Add(new Food { FoodName = "Творожная масса с цукатами", Proteins = 7, Fat = 21, Carbohydrates = 33, CaloricValue = 349 });
//            products.Add(new Food { FoodName = "Тесто дрожжевое", Proteins = 7, Fat = 4, Carbohydrates = 43, CaloricValue = 238 });
//            products.Add(new Food { FoodName = "Тесто слоеное дрожжевое", Proteins = 7, Fat = 19, Carbohydrates = 40, CaloricValue = 356 });
//            products.Add(new Food { FoodName = "Тесто слоёное бездрожжевое", Proteins = 6, Fat = 18, Carbohydrates = 38, CaloricValue = 335 });
//            products.Add(new Food { FoodName = "Томатная паста помидорка", Proteins = 1, Fat = 0, Carbohydrates = 15, CaloricValue = 77 });
//            products.Add(new Food { FoodName = "Томаты черри", Proteins = 1, Fat = 0, Carbohydrates = 3, CaloricValue = 17 });
//            products.Add(new Food { FoodName = "Треска филе", Proteins = 17, Fat = 1, Carbohydrates = 0, CaloricValue = 78 });
//            products.Add(new Food { FoodName = "Тушенка говядина высший сорт", Proteins = 15, Fat = 17, Carbohydrates = 0, CaloricValue = 213 });
//            products.Add(new Food { FoodName = "Тыква", Proteins = 1, Fat = 0, Carbohydrates = 5, CaloricValue = 22 });
//            products.Add(new Food { FoodName = "Урюк (сухофрукты)", Proteins = 5, Fat = 0, Carbohydrates = 51, CaloricValue = 213 });
//            products.Add(new Food { FoodName = "Фарш говяжий", Proteins = 18, Fat = 16, Carbohydrates = 0, CaloricValue = 214 });
//            products.Add(new Food { FoodName = "Фарш куриный", Proteins = 19, Fat = 10, Carbohydrates = 0, CaloricValue = 166 });
//            products.Add(new Food { FoodName = "Фасоль", Proteins = 18, Fat = 1, Carbohydrates = 44, CaloricValue = 263 });
//            products.Add(new Food { FoodName = "Фасоль стручковая", Proteins = 2, Fat = 0, Carbohydrates = 4, CaloricValue = 29 });
//            products.Add(new Food { FoodName = "Финики (сухофрукты)", Proteins = 2, Fat = 0, Carbohydrates = 72, CaloricValue = 380 });
//            products.Add(new Food { FoodName = "Фруктоза", Proteins = 0, Fat = 0, Carbohydrates = 100, CaloricValue = 390 });
//            products.Add(new Food { FoodName = "Фундук", Proteins = 15, Fat = 62, Carbohydrates = 11, CaloricValue = 665 });
//            products.Add(new Food { FoodName = "Хлеб белый", Proteins = 8, Fat = 3, Carbohydrates = 54, CaloricValue = 254 });
//            products.Add(new Food { FoodName = "Хлеб \"бородинский\"", Proteins = 7, Fat = 1, Carbohydrates = 42, CaloricValue = 210 });
//            products.Add(new Food { FoodName = "Хлеб пшеничный", Proteins = 8, Fat = 3, Carbohydrates = 50, CaloricValue = 263 });
//            products.Add(new Food { FoodName = "Хлеб ржаной", Proteins = 7, Fat = 1, Carbohydrates = 36, CaloricValue = 187 });
//            products.Add(new Food { FoodName = "Хлебцы пшеничные", Proteins = 12, Fat = 2, Carbohydrates = 60, CaloricValue = 305 });
//            products.Add(new Food { FoodName = "Хлопья кукурузные", Proteins = 7, Fat = 1, Carbohydrates = 84, CaloricValue = 373 });
//            products.Add(new Food { FoodName = "Хлопья овсяные", Proteins = 12, Fat = 6, Carbohydrates = 52, CaloricValue = 308 });
//            products.Add(new Food { FoodName = "Хрен", Proteins = 3, Fat = 5, Carbohydrates = 14, CaloricValue = 113 });
//            products.Add(new Food { FoodName = "Хурма", Proteins = 1, Fat = 0, Carbohydrates = 15, CaloricValue = 65 });
//            products.Add(new Food { FoodName = "Цветная капуста отварная", Proteins = 2, Fat = 0, Carbohydrates = 4, CaloricValue = 29 });
//            products.Add(new Food { FoodName = "Цедра апельсина", Proteins = 1, Fat = 0, Carbohydrates = 6, CaloricValue = 36 });
//            products.Add(new Food { FoodName = "Цедра лимона", Proteins = 1, Fat = 0, Carbohydrates = 4, CaloricValue = 28 });
//            products.Add(new Food { FoodName = "Цукаты", Proteins = 3, Fat = 0, Carbohydrates = 56, CaloricValue = 224 });
//            products.Add(new Food { FoodName = "Цукини", Proteins = 2, Fat = 0, Carbohydrates = 3, CaloricValue = 18 });
//            products.Add(new Food { FoodName = "Черемша", Proteins = 2, Fat = 0, Carbohydrates = 7, CaloricValue = 37 });
//            products.Add(new Food { FoodName = "Черешня", Proteins = 1, Fat = 0, Carbohydrates = 12, CaloricValue = 51 });
//            products.Add(new Food { FoodName = "Черника", Proteins = 1, Fat = 0, Carbohydrates = 9, CaloricValue = 39 });
//            products.Add(new Food { FoodName = "Чернослив (сухофрукты)", Proteins = 3, Fat = 0, Carbohydrates = 62, CaloricValue = 256 });
//            products.Add(new Food { FoodName = "Чеснок", Proteins = 6, Fat = 0, Carbohydrates = 23, CaloricValue = 115 });
//            products.Add(new Food { FoodName = "Чечевица зелёная", Proteins = 24, Fat = 2, Carbohydrates = 44, CaloricValue = 286 });
//            products.Add(new Food { FoodName = "Чечевица красная", Proteins = 22, Fat = 1, Carbohydrates = 49, CaloricValue = 312 });
//            products.Add(new Food { FoodName = "Шампиньоны", Proteins = 4, Fat = 1, Carbohydrates = 1, CaloricValue = 26 });
//            products.Add(new Food { FoodName = "Шампиньоны резанные консервированные", Proteins = 2, Fat = 1, Carbohydrates = 1, CaloricValue = 16 });
//            products.Add(new Food { FoodName = "Шиповник сушёный", Proteins = 4, Fat = 0, Carbohydrates = 60, CaloricValue = 253 });
//            products.Add(new Food { FoodName = "Шоколад горький 75%", Proteins = 9, Fat = 41, Carbohydrates = 39, CaloricValue = 550 });
//            products.Add(new Food { FoodName = "Шоколад горький 80%", Proteins = 12, Fat = 39, Carbohydrates = 34, CaloricValue = 527 });
//            products.Add(new Food { FoodName = "Шоколад молочный", Proteins = 7, Fat = 34, Carbohydrates = 52, CaloricValue = 539 });
//            products.Add(new Food { FoodName = "Шпинат", Proteins = 3, Fat = 0, Carbohydrates = 2, CaloricValue = 22 });
//            products.Add(new Food { FoodName = "Щавель", Proteins = 2, Fat = 0, Carbohydrates = 5, CaloricValue = 25 });
//            products.Add(new Food { FoodName = "Яблоки", Proteins = 1, Fat = 1, Carbohydrates = 13, CaloricValue = 60 });
//            products.Add(new Food { FoodName = "Яблоки сушёные (сухофрукты)", Proteins = 3, Fat = 0, Carbohydrates = 66, CaloricValue = 269 });
//            products.Add(new Food { FoodName = "Яйца", Proteins = 15, Fat = 13, Carbohydrates = 1, CaloricValue = 162 });



//            context.Products.AddRange(products);
//            context.SaveChanges();

//            //IList<MyPlate> plates = new List<MyPlate>();
//            ////  plates.Add(new MyPlate { mealtime = new DateTime(2015, 5, 17), PlateFoodId = 1 });
//            ////  plates.Add(new MyPlate { mealtime = new DateTime(2015, 5, 17), PlateFoodId = 2 });
//            ////plates.Add(new MyPlate { FoodId = 1, MealTime = mt1 });
//            ////plates.Add(new MyPlate { FoodId = 2, MealTime = mt1 });
//            ////plates.Add(new MyPlate { FoodId = 4, MealTime = mt2 });
//            ////plates.Add(new MyPlate { FoodId = 3, MealTime = mt2 });

//            //context.MyPlates.AddRange(plates);
//            //context.SaveChanges();

//            //IList<PlateFoodRecord> plateFoodRecord = new List<PlateFoodRecord>();
//            //plateFoodRecord.Add(new PlateFoodRecord { FoodId = 1, PlateId = 1, Weight = 185 });
//            //plateFoodRecord.Add(new PlateFoodRecord { FoodId = 5, PlateId = 1, Weight = 350 });
//            //plateFoodRecord.Add(new PlateFoodRecord { FoodId = 2, PlateId = 1, Weight = 100 });
//            //plateFoodRecord.Add(new PlateFoodRecord { FoodId = 3, PlateId = 1, Weight = 220 });
//            //plateFoodRecord.Add(new PlateFoodRecord { FoodId = 6, PlateId = 2, Weight = 400 });
//            //plateFoodRecord.Add(new PlateFoodRecord { FoodId = 4, PlateId = 2, Weight = 110 });
//            //plateFoodRecord.Add(new PlateFoodRecord { FoodId = 8, PlateId = 2, Weight = 290 });

//            //context.PlateFoodRecords.AddRange(plateFoodRecord);
//            //context.SaveChanges();
//            // base.Seed(context);
//        }
//    }
//}
